### ISSUE TITLE
[BUG] The back arrow in the upper left of settings does not work.

### ISSUE THREAD

**Issue by IeanD** [AFRUITPIE/Conversation-Starter#6]
**Reproduce**:
1. Open conversation starter
2. Select the three-dot menu, then select 'Settings'
2. Select the left-facing arrow in the top right of the application

**Expected result**:
1. The user is returned to Conversation Starter's main menu.

**Actual result**:
1. Nothing happens.

**Comment by AFRUITPIE** [comment]
Corrected by overriding `onOptionsItemSelected` in the Settings activity
